name: CI/CD – Build & Deploy to CT

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. 先把原始碼拉下來
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 切到 backend 資料夾，build image
      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t backend:latest .

      # 3. 把 image 存成 tar
      - name: Save image to TAR
        run: |
          docker save -o backend.tar backend:latest

      # 4. SCP 送到 CT
      - name: Copy TAR to CT
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CT_HOST }}
          username: ${{ secrets.CT_USER }}       # 通常是 root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "backend.tar"
          target: "/root/monitoring/"

      # 5. SSH 到 CT 上做部署（load、rm、docker compose up）
      - name: Deploy on CT
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CT_HOST }}
          username: ${{ secrets.CT_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 切到目錄
            cd /root/monitoring

            # 將新 image 載入
            docker load -i backend.tar

            # 重啟服務
            docker compose up -d